# Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
  labels:
    app: node-app
type: Opaque
data:
  DB_USER: YXBwdXNlcgo=                  # appuser
  DB_PASSWORD: cGFzc3dvcmQxMjMK          # password123
