# Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dev
  labels:
    app: backend
type: Opaque
data:
  user: YXBwdXNlcgo=                  # appuser
  password: cGFzc3dvcmQxMjMK          # password123
  jwt-secret: "your-jwt-secret-key"
