# Service Account with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/ExternalSecretsRole

---
# SecretStore with IRSA
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa     # Service account with IAM role

---
# ExternalSecret with individual key mapping
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:                              # Individual key mapping
    - secretKey: DB_USER             # K8s Secret key
      remoteRef:
        key: dev-db-credentials      # AWS Secret name
        property: username           # JSON property
    
    - secretKey: DB_PASSWORD
      remoteRef:
        key: dev-db-credentials
        property: password
    
    - secretKey: DB_HOST
      remoteRef:
        key: dev-db-credentials
        property: host
    
    - secretKey: DB_PORT
      remoteRef:
        key: dev-db-credentials
        property: port

    - secretKey: DB_NAME
      remoteRef:
        key: dev-db-credentials
        property: database
