#=========================================================
# External Secrets Operator - AWS SecretsManager via IRSA
# maps AWS Secret JSON keys to Kubernetes Secret keys
#=========================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: dev
  labels:
    app: backend
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore

  target:
    name: db-secret
    creationPolicy: Owner

    # When ExternalSecret deleted:
    # - Retain = keep generated secret (avoid accidental delete)
    # - Delete = remove generated secret too
    deletionPolicy: Retain

    # Optional: add labels/annotations to generated secret
    template:
      metadata:
        labels:
          app: backend

  data:                              # Individual key mapping
    - secretKey: DB_USER             # K8s Secret key
      remoteRef:
        key: dev-db-credentials      # AWS Secret name
        property: username           # JSON property
    
    - secretKey: DB_PASSWORD
      remoteRef:
        key: dev-db-credentials
        property: password
    
    - secretKey: DB_HOST
      remoteRef:
        key: dev-db-credentials
        property: host
    
    - secretKey: DB_PORT
      remoteRef:
        key: dev-db-credentials
        property: port

    - secretKey: DB_NAME
      remoteRef:
        key: dev-db-credentials
        property: database
