#============================
# Service Account with IRSA
#============================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: dev
  labels:
    app: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/ExternalSecretsRole
