# MySQL Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
  labels:
    app: mysql-db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=         # rootpass
  MYSQL_PASSWORD: cGFzc3dvcmQxMjM=          # password123
