# MySQL Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
  labels:
    app: mysql-db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3MK         # rootpass
  MYSQL_USER: YXBwdXNlcgo=                  # appuser
  MYSQL_PASSWORD: cGFzc3dvcmQxMjMK          # password123
