#======================================
# ServiceAccount for Jenkins Pipeline
#======================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: webapps
